name: Update gist with most used programming languages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # ë§¤ì¼ ìì • UTC

jobs:
  language-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Update language gist
        run: pnpm dlx github-lang-box@2
        env:
          GH_USERNAME: harim061        # â† ë³¸ì¸ ì•„ì´ë””
          GIST_ID: 9e76b15c0c5cd4826bd4b040a03f3130
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EXCLUDE: ${{ vars.EXCLUDE }}
          EXCLUDE_REPO: ${{ vars.EXCLUDE_REPO }}
          DESCRIPTION: ğŸ’» Most used languages
