name: Update gist with most used programming languages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  language-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update language gist
        run: npx github-lang-box@2
        env:
          GH_USERNAME: harim061
          GIST_ID: 8335e85451541072dd25fda601129f7d
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EXCLUDE: ${{ vars.EXCLUDE }}
          EXCLUDE_REPO: ${{ vars.EXCLUDE_REPO }}
          DESCRIPTION: ðŸ’» Most used languages
